### ISSUE TITLE
Clarification on Inference engines

### ISSUE THREAD

**Issue by akashsonowal** [gradsflow/fastserve-ai#65]
Hi @aniketmaurya 

In all the inference engines that's behind the serving layer. I see the individual items in a batch are still processed individually inside a for loop. Is it for handling scenarios where user doesn't have GPUs?

Thanks,

Akash

**Comment by aniketmaurya** [comment]
hi @akashsonowal, the example might only be for demonstration. [Here](https://github.com/gradsflow/fastserve-ai/blob/aa5bb0bfed6308799d069a6bd73a28ff25166e62/src/fastserve/models/cv/image_classification.py#L65) is a model that uses batched prediction.
